### ISSUE TITLE
Include publication site in README

### ISSUE THREAD

**Issue by EdwinTh** [ropenscilabs/tic.bookdown#2]
If you are unfamiliar with github pages you are probably not aware that the book is published at https://ropenscilabs.github.io/tic.bookdown/ and that it is build from the gh-pages branch that is added to the repo by Travis CI. It took me some time to figure this out and I am not even new to Travis. Would be nice if the README elaborated a bit more on this.

**Comment by pat-s** [comment]
Thanks. I added some instructions to the README.
